# -*- coding: utf-8 -*-
"""task2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAjGqHpzjF68tzW11yDJNQCv1E779Ihc
"""

#task 2 b
'''
to do the task in o(n). i have just made used the previous codes marge funciton.
 in marge function from two list i have checked if one value is smaller then then the other lists pointers value.and in new list added a the smallest value. then moved
the pointer after doing these continiousy. if there are
still number in the remaing list.then added the whole list at the end of the new list.
'''

#for opening file
boi= open ("input2b.txt","r")
khata= open("output_2b.txt","w")

num1=int(boi.readline())
box1 = list(map(int,boi.readline().split()))
num2=int(boi.readline())
box2 = list(map(int,boi.readline().split()))
print()
newbox = []
first, last = 0, 0
for i in range(num1 + num2):
    if first>=len(box1):
        newbox+=box2[last:]
        break
    elif last>=len(box2):
        newbox+=box1[first:]
        break

    elif int(box1[first]) > int(box2[last]):
        newbox.append(box2[last])
        last += 1
    else:
        newbox.append(box1[first])
        first += 1
    print(newbox, first, last)



print(newbox)
x=newbox
khata.write(" ".join(map(str, x)))
print(" ".join(map(str, x)))
boi.close()
khata.close()