# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAjGqHpzjF68tzW11yDJNQCv1E779Ihc
"""

#task 1 b
'''
for solving this problem I have used two pointers tecnique. at first i have taken two pointers one at first and other at
the last. then checked if these two pointers sum is equal to two the number or not.if yes then i have returned the position
 by adding one as it is a one based indexing. then if it is not i have checked if the sum is smaller than the given number
 or not if yes , then i need to increase the sum so i have moved the pointer right . befor if i the number was bigger then
 to make the sum  smaller i should have moved the right pointer left just to make the sum more.
'''
#for opening file
boi= open ("input1b.txt","r")
khata= open("output_1b.txt","w")

x,y=boi.readline().split()
box = boi.readline().split()
x,y=int(x),int(y)
print(x ,y)

def sum_check2(box,y):
    first, last = 0,len(box)-1

    while first < last:
        sum = int(box[first])+int(box[last])
        if sum == y:
            khata.write(f"{first+1} {last+1}")
            print(f"{first+1} {last+1}")
            return

        elif sum > y:
            last-=1
        elif sum < y :
            first+=1
    khata.write(f"IMPOSSIBLE")
    print(f"IMPOSSIBLE")
sum_check2(box,y)

boi.close()
khata.close()