# -*- coding: utf-8 -*-
"""task2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAjGqHpzjF68tzW11yDJNQCv1E779Ihc
"""

#task 2 a
'''
at first i have just made a list by adding two given list.
then i have sored using marge sort to make it o(nlogn).
to do the marge sort i have made two function one two marge
other to dive (by applying divide and conquere rule)

'''
#for opening file
boi= open ("input2a.txt","r")
khata= open("output_2a.txt","w")

num1=int(boi.readline())
box1 = boi.readline().split()
num2=int(boi.readline())
box2 = boi.readline().split()

newbox = box1 + box2
def merge(box1, box2):
       # write your code here
     	 # Here a and b are two sorted list
       # merge function will return a sorted list after merging a and b

    newbox = []
    first, last = 0, 0
    for i in range(len(box1) + len(box2)):
        if first>=len(box1):
            newbox+=box2[last:]
            break
        elif last>=len(box2):
            newbox+=box1[first:]
            break

        elif int(box1[first]) > int(box2[last]):
            newbox.append(box2[last])
            last += 1
        else:
            newbox.append(box1[first])
            first += 1
        #print(newbox, first, last)
    return newbox


def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr)//2
        a1 = mergeSort(arr[: mid])  # write the parameter
        a2 = mergeSort(arr[ mid:])  # write the parameter
        return merge(a1, a2)          # complete the merge function above
print(" ".join(map(str, newbox)))
x=mergeSort(newbox)
khata.write(" ".join(map(str, x)))
print(" ".join(map(str, x)))

boi.close()
khata.close()