# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAjGqHpzjF68tzW11yDJNQCv1E779Ihc
"""

#task 3
'''
for these task i have made two list one for starting and other for the
ending time of the shedule. then i have sorted these two list on the
 basis of ending time. then statted to take a job  from the first and printing it
'''
#for opening file
boi= open ("input3.txt","r")
khata= open("output_3.txt","w")

start = []
last = []

num=int(boi.readline())
#just to making two list
for i in range(num):
    x, y = list(map(int,boi.readline().split()))
    start.append(x)
    last.append(y)
n= len(last)
#the sorting loop

for i in range(n):
        # Last i elements are already in place, so we don't need to compare them again
        for j in range(0, n-i-1):
            # Traverse the array from 0 to n-i-1, swap if the element found is greater than the next element
            if last[j] > last[j+1]:
                last[j], last[j+1] = last[j+1], last[j]
                start[j], start[j+1] = start[j+1], start[j]

for i in range(num):
    print(start[i], last[i])

print("--------")
f=0
l=0
count=0
for i in range(num):
    if start[i]>=l:
        count+=1

        l=last[i]
khata.write(f"{count} \n")
f=0
l=0
for i in range(num):
    if start[i]>=l:
        print( start[i], last[i])
        khata.write(f"{start[i]} {last[i]} \n")
        l=last[i]