# -*- coding: utf-8 -*-
"""Task1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu9p3IrVfuclMGLf4xT5Zd8hZjXhOsYO

**task 1 (a) explanation**--
with f1 and f2 varible the code opens two file one for reading(input) and other for writing(output).then "a" reads test case number. then with the loop it reads a line at a time and chack if its is even or odd by moding the number with 2  and writes the output in the output file. and then i have close both of the files.
"""

#task 1 a
#for opening file
f1= open ("input1a.txt","r")
f2= open("output_1a.txt","w")

a=int(f1.readline())
for i in range(a):
    x=int(f1.readline())
    if x%2==0:
        f2.write(f"{x} is an Even number\n")
    else:
        f2.write(f"{x} is an odd number\n")
f1.close()
f2.close()