# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu9p3IrVfuclMGLf4xT5Zd8hZjXhOsYO

**Task 3**---
we know Selection sorting sort a list with minimum numbers of swaping. after reading the input file i have made two list one for ID and other for numbers.then with selection sort i have sorted the two list with the numbers . inside the sorting algo when the id number is same it swaps position if the id number id in the first list is small. other wise it don't swaps.
"""

#task 3 final one

#for opening file
boi= open("input3.txt","r")
khata= open("output_3.txt","w")

num=int(boi.readline())

#for file reading part
s1=boi.readline()
s2=boi.readline()

box1=s1.split()
box2=s2.split()
#sorting part

a=box2
b=box1
for i in range(len(a)):


    idx=i
    for j in range(i+1, len(a)):
        if a[j]>a[idx]:

            idx=j
        elif  a[j]==a[idx]:

            idx=j


    #for the 2nd condition when number is same.
    if a[j]==a[idx]:
        if b[j]>b[idx]:
            a[i], a[idx] = a[idx], a[i]
            b[i], b[idx] = b[idx], b[i]
    #just to swap  two list , with numbers
    else:

        a[i], a[idx] = a[idx], a[i]
        b[i], b[idx] = b[idx], b[i]

#printing part
for i in range(len(box1)):
    print(f"ID: {box1[i]} Mark: {box2[i]}")
    khata.write(f"ID: {box1[i]} Mark: {box2[i]}\n")

boi.close()
khata.close()