# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu9p3IrVfuclMGLf4xT5Zd8hZjXhOsYO

**task 2**--
we know bubble sort performs in O(n**) time complexity. so to make in O(n) it is only possible when it performs in best case .means that when the test case is already given.for checking the best case i have used flag. if becomes false when one swap operation is done these means that it is not base case.
"""

#task 2

#for opening file
boi= open("input2.txt","r")
khata= open("output_2.txt","w")

num=int(boi.readline())
#for sorting part
stack=boi.readline()
box=stack.split()

def bubbleSort(arr):

    for i in range(len(arr)-1):
        chabi=True
        print(arr)

        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                chabi=False
        if chabi:
            s=" ".join(arr)
            return khata.write(s)

    s=" ".join(arr)
    print(s)
    return khata.write(s)



bubbleSort(box)

boi.close()
khata.close()